### ISSUE TITLE
csi: Create CSI->Docker southbound bridge

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/rexray#1037]
This Epic tracks issues related to creating a new southbound adapter that would translate incoming requests to the docker volume module to a CSI plugin (bypassing libStorage). This means that any CSI plugin could be accessed via Docker, given that CO a way to consume CSI plugins before CSI is supported natively.

**Comment by clintkitson** [comment]
General question regarding this one. Which CSI plugin are we targeting that does not already have a Docker plugin?

**Comment by akutz** [comment]
Hi Clint,

I'm sorry you missed last week's meeting as the reasons behind this strategic decision were discussed then. The following is the best I can provide from memory (not in front of my computer):

- It provides a bridge from old to new 
- That allows us to focus on porting drivers to CSI
- Fixing outstanding bugs
- Creating new features 
- All focused on CSI while still providing value and support for existing customers
- Especially given that there is no CO that supports CSI yet and we cannot rely on when that will occur

Josh recognized due to our engineering resources We were faced with two choices:

1. Back off all new CSI development in favor of handling existing issues/features focused on libStorage
2. Focus on CSI, a checkbox for the moment sans value to existing customers

We suggested that a CSI->Docker bridge would allow us to focus on the future (CSI) while still continuing to provide fixes and new value for existing customers.

Hopefully the above provides some insight to this decision. I know it's a 180 from what you and I previously discussed. I almost even texted you, but I didn't want to interrupt your vacation.

Anyway, I will be more than happy to chat with you further about this when we next speak. Maybe we missed something entirely, and the above plan is constructed on a shaky foundation. I look forward to your input.

**Comment by akutz** [comment]
Hi @codenrhoden (cc @clintkitson),

Per our discussion on Friday, we plan to use revision  [`8dbb732`](https://github.com/container-storage-interface/spec/tree/8dbb73222cdb63ce583e5c0abeafdf96748bf4f5) of the CSI spec to implement the southbound adapter. This version lacks the addition of the `VolumeHandle`, but we agreed we cannot risk updating GoCSI and REX-Ray based on the following unresolved design decisions/changes:
* container-storage-interface/spec#116
* container-storage-interface/spec#117
* container-storage-interface/spec#118

Without the above resolution, CSI plug-ins must ensure that `CreateVolume` and `ListVolumes` return `VolumeInfo` objects that contain the following data where applicable:

| Object | Field | Description |
|--------|------|-------------|
| `VolumeInfo.Id.Values` | `id` | A `string` that uniquely identifies a volume |
| | `name` | A `string` that represents a volume's friendly name |

However, after working on the bridge it has occurred to me we need to include an additional piece of data:

| Object | Field | Description |
|--------|------|-------------|
| `VolumeInfo.Metadata.Values` | `mountpaths` | A comma-separated list of the filesystem paths to to which the volume is mounted |

@codenrhoden / @clintkitson, I need your input. Today `docker volume create VOLUME_NAME` only supports a single volume-to-device-to-target-path relationship. However, CSI technically enables a volume to be mounted on the filesystem at **multiple** target paths. The questions I'm posing are: 

* **Does the Docker->CSI bridge assume that a volume can only ever be mounted once on the local node?**
* **If not, then how should the bridge handle the case where the volume is mounted multiple times?**

The above situation is clearly one of whether the bridge attempts to support the CSI **model** in addition to using its API. The CSI model supports multiple mounts per volume. Docker does not.

**Is the bridge enforcing Docker's rules on CSI, or should we figure out how to make the bridge play by CSI's rules?**
