### ISSUE TITLE
Reset passwords that were saved in clear text as an encrypted string

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/rexray#172]
It would be nice to reset any passwords that are set in the `rexray.yml` file to an encrypted string that is based off a lockbox associated to the OS instance.

**Comment by akutz** [comment]
I think you mean `config.yml`, but yes, I agree.

**Comment by akutz** [comment]
I'm closing this ticket as it should be refiled as requesting a secure store for credentials and other sensitive information. The current issue implies that such a thing exists and we want to move existing passwords to it when in fact no such thing exists yet. It would be OS dependent if it did, and must be given more thought. This issue is getting ahead of things to the point that it will be ignored. Once a secure store is created, documentation will be provided to instruct people how to move credentials and other sensitive information to said store.

**Comment by clintonskitson** [comment]
This is a bookmark for a requested feature for encrypting passwords as secure strings that are stored in local files.

**Comment by akutz** [comment]
Then please rewrite the issue's subject and description to say that instead of describing a different issue. Otherwise close this issue and please open a new one that accurately describes the requested feature. 

However, I will say that at no point will passwords be reset or automatically stored in a secure location from existing files. We will provide documentation to set up secure stores, but automating such a task is has too much potential for problems and opens up attack vectors.

-- 
-a

**Comment by clintonskitson** [comment]
Let's hold off on the judgement on how the feature would behave.

**Comment by akutz** [comment]
As the project lead l'll be the one deciding implementations, so I'm comfortable making those judgements. That with which I do not feel comfortable is using the issue tracker to bookmark issues incorrectly reported. Such issues should be closed, rewritten, or reopened with a more accurate description of the actual problem and use case to which it relates. As my manager it's of course your prerogative to do otherwise, but if you have items you wish to track for yourself, I'd ask you do so in a private issue track and trust me to manage those in the project's tracker.

-- 
-a
