### ISSUE TITLE
rexray volumes with no name are shown on get-volume

### ISSUE THREAD

**Issue by kacole2** [codedellemc/rexray#29]
Would it be a good idea to not retrieve volumes that do not have names? For instance `""`.

Other idea is to have a flag that retrieves everything, including volumes with `""` no names.

**Comment by clintonskitson** [comment]
I can see this related to https://github.com/emccode/rexray/issues/28.  Yes, since we rely on the name of a volume as its uniqueness, something like a blank name shouldn't be valid.  Different underlying storage platforms may or may not allow blank names.  In the case of EC2 it defaults to blank, which misaligns to the uniqueness RR relies on in the name.  I think the EC2 driver can address this.
