### ISSUE TITLE
EC2: add support for encrypted volumes

### ISSUE THREAD

**Issue by rvalkenaers** [codedellemc/rexray#298]
It would be nice if we could create encrypted volumes. It shouldn't be too hard as https://github.com/mitchellh/goamz already supports this.

**Comment by clintonskitson** [comment]
@rienvalkenaers Thank you for the request. We use https://github.com/goamz/goamz which does not include the encrypted support yet, they are similar packages though so porting wouldn't be a problem. We need to investigate this further to figure out where it would fit in the model since today we specify `volumeType`, `IOPS`, and `availabilityZone` for volumes. It would seem to make sense to declare it as another create option for `encrypted` for volume operations and the actual volume object itself. The other thing to consider is whether storage platforms in general would consistently provide this feature, which I believe would be an accurate statement.

We have also been considering the in-guest fuse based encryption method. This could be complimentary if applied to the `mount` operations where the volume map would specify it being attached/mounted including encryption.

**Comment by codenrhoden** [comment]
Addressed by codedellemc/libstorage#355
