### ISSUE TITLE
[Question] Volume mapping for Nomad

### ISSUE THREAD

**Issue by linusviking** [codedellemc/rexray#342]
Has anyone tried volume mapping on Docker containers on Nomad (https://www.nomadproject.io/) and share some experience?

**Comment by clintonskitson** [comment]
Hello @linusviking!

It looks like the relevant thread in Nomad is https://github.com/hashicorp/nomad/issues/150

The idea was being thrown around for how to actually enable this. Today there is no support since Nomad doesn't have persistent support and it does not allow arbitrary parameters when running `docker run` commands.
