### ISSUE TITLE
docker looks for volumes even though they don't exist

### ISSUE THREAD

**Issue by clubanderson** [codedellemc/rexray#381]
scenario:
 scaleio 2.0

Install Scaleio (MDM, TB, SDC, SDS, GUI)
Start docker container that maps a volume (test:/etc/test)
Destroy scaleio (or just remove volume)
Restart docker

Docker will insist that a volume should exist and should not be created.  If you look in dockers volume/metadata.db you will see that docker thinks a volume should exist.  

Resolution: if docker believes the volume should exist, than create the volume.  Right now rexray/scaleio returns "cannot retrieve volume by name".

I have tried cleaning up the docker volumes (dangling), however sometimes the volumes are not listed and yet they are still in the metadata.db.  Rexray can create instead of fail (maybe based on a switch in config? - force_create)

**Comment by clintonskitson** [comment]
@clubanderson I believe it is actually Docker that is failing because they believe the volume exists already. The "dangling" volume is on the Docker side where containers that still exist that were attached to volumes create a problem.

On the RR side, if you create the volume from the `rexray` command I am assuming there are no problems.

You could also try creating the volume using `dvdcli` which simulates how Docker talks with REX-Ray through it's HTTP/JSON interface. I am assuming that would also yield no problem.

This could turn out to be an issue that needs to be raised with Docker.
