### ISSUE TITLE
Ceph

### ISSUE THREAD

**Issue by thbeh** [codedellemc/rexray#390]
Hi, this is not actually an issue but just to find out whether can I use rex-ray as a driver to docker/mesos to attached  a ceph/rbd disk?

**Comment by clintonskitson** [comment]
We don't have a driver yet but would be interested if someone was to contribute one.

**Comment by thbeh** [comment]
So currently I am using contiv's  volplugin driver for my docker container (which mount my ceph pool).  Not sure whether that driver works with rexray.

Alternatively I could use filesystem created on top of Ceph but would rexray able to use with host filesystem (I did not see any examples doing so)?

**Comment by clintonskitson** [comment]
For a driver to work with RR it must be written to satisfy what RR expects from methods. So because it works in another package doesn't mean it works in RR. For Ceph to work, there needs to be some translation between other drivers.

**Comment by thbeh** [comment]
Ok. noted. Will see how to move forward using RR. Thank.

I can close this.

**Comment by tobilg** [comment]
Probably it would also make sense to have a look at [h0tbird/docker-volume-rbd](https://github.com/h0tbird/docker-volume-rbd) as a starting point. I'd be really happy if Ceph could be supported in RexRay. I think this would be beneficial to the project, because IMHO there is a large user base of Ceph.

**Comment by a-nldisr** [comment]
It should be possible to place Ceph as a volume driver in cinder and expose rbd's through Cinder that way. At this very moment i am setting up a Cinder environment (with galera and keystones) on Mesos to test this theory.

**Comment by thbeh** [comment]
There' a standalone Ceph sandbox that can be created easily without Cinder
- https://github.com/ceph/ceph-docker

I am using this to test Ceph and workable binding to block devices. But I
just not sure how to integrate with RR/Mesos.

**Comment by kacole2** [comment]
@tobilg @a-nldisr @thbeh i just wanted to let you know that this issue is being tracked in [libStorage 191](https://github.com/emccode/libstorage/issues/191). All new drivers are going to be built into libStorage and all drivers for REX-Ray have been ported over as well. 

If you plan on submitting PRs to add in a Ceph driver please refer to that repo and codebase. thanks!

**Comment by codenrhoden** [comment]
Ceph RBD support has been added with REX-Ray v0.7.0.
