### ISSUE TITLE
CLI should reject request to create volume without size param

### ISSUE THREAD

**Issue by vladimirvivien** [codedellemc/rexray#536]
Currently the following will work (but backend will reject request).

```
$>rexray volume create --volumename="somename"
```

Most storage backend require a size when creating a volume, the CLI probably should do the same.

**Comment by akutz** [comment]
Hi @vladimirvivien,

I would normally agree except REX-Ray and libStorage both understand and support the concept of a default size. That's why the lack of the flag is not rejected.

**Comment by vladimirvivien** [comment]
@akutz 
I thought that was the case as well, but I just redid this test against the latest rexray without the size param and it failed.  This is using the scaleio driver.  The driver got size=0.  Should this be a bug against libStorage ?

```
$> rexray volume create --volumename="vol-test-rexray" -l debug
...
RRO[0001] error creating volume                         IOPS=0 availabilityZone= host=unix:///var/run/libstorage/282555454.sock inner=problem getting response: Wrong command parameters. You can check that you are using the correct parameters, by consulting the help for the command. instanceID=scaleio=0720519500000000 provider=scaleIO route=volumeCreate server=puzzle-pixie-sr service=scaleio size=0 task=0 time=1471482712815 tls=false txCR=1471482712 txID=995a32b1-9ec2-41c2-708d-a461f2b3ec2a volumeName=vol-test-rexray volumeType=default
```

**Comment by akutz** [comment]
I don't know. Please re-execute using all available logging. Use the tip of REX-Ray and execute the command using the embedded mode with `REXRAY_DEBUG=true` prefixed on the command line. This enables all available debug logging. It will show what is being sent and consumed between the libStorage client and server.

The config value [*is* registered](https://github.com/emccode/libstorage/blob/master/drivers/integration/docker/docker.go#L588) with a default value of 16. I didn't write this code, and I want to refactor it anyway so that it is no longer registered as some randomly-GB value. We should support size suffixes to indicate MB or GB, etc. 

My initial thought is the bug could be in REX-Ray. If the `size` flag is not provided, the value parsed from it is 0.

**Comment by akutz** [comment]
And that's what is happening. The `size` [field](https://github.com/emccode/rexray/blob/master/rexray/cli/cli.go#L98) in REX-Ray is an `int64`, so if the value is not provided it will always be zero. We *could* make this a pointer to an integer so it can be nil. However, I didn't write any of this code. The config value should *not* be a string when this value is an integer. We should make the CLI value a *string* and parse it as a size with allowed suffixes. If the string is empty, the CLI flag not set, we simply don't pass the value to libStorage instead of providing a value of 0 as we are doing now.

**Comment by codenrhoden** [comment]
Would a reasonable approach for this be to make sure that each storage driver has a default size value, built into the driver (and overridable via config).  The `linux` integration driver has a default size of 16GB, but if you don't go through the integration driver, a size 0 volume request can appear at the driver.  Some drivers reject this outright, some drivers defer to a default size, and yet still more (ahem, `rbd` gladly pass this to the backend storage).

I think having a per-driver default size might be a good idea. Several providers have minimums that must be met as well.

**Comment by akutz** [comment]
Hi @codenrhoden,

Hmmm. Maybe... Remember that REX-Ray is a client, libStorage is the API. The client, IMO, should not be important to the API to this extent. The integration driver is also client side an not at all required. For example, the client @vladimirvivien created for K8 doesn't use it.

I like your suggestion, but here's a spin on it. Just as the integration driver has defaults, perhaps what we need to introduce are defaults for the API's request parameters that a driver can elect to also override. For example:

```yaml
libstorage:
  server:
    api:
      volumes:
        create: 
          size: 10GB
  services:
    ebs-00:
      driver: ebs
    ebs-01:
      driver: ebs
      libstorage:
        server:
          api:
            volumes:
              create:
                size: 15GB
```

When the driver code requests the property `libstorage.server.api.volumes.create.size` when responding to a request issued to the `ebs-00` service, the result will be `10GB`. However, if a request is sent to the `ebs-01`, the property `libstorage.server.api.volumes.create.size` has a value of `15GB`.

These values would be defaults and only used if a request omits a property. I imagine this would be implemented at the server's router level instead of by individual drivers since, if implemented at the router level, the drivers don't have to duplicate code. It would be fairly trivial to do so in [`volume_routes.go`](https://github.com/codedellemc/libstorage/blob/master/api/server/router/volume/volume_routes.go#L380-L403), with some changes similar to the following:

```go
func (r *router) volumeCreate(
	ctx types.Context,
	w http.ResponseWriter,
	req *http.Request,
	store types.Store) error {

	service := context.MustService(ctx)

	run := func(
		ctx types.Context,
		svc types.StorageService) (interface{}, error) {

		opts := &types.VolumeCreateOpts{
			AvailabilityZone: store.GetStringPtr("availabilityZone"),
			IOPS:             store.GetInt64Ptr("iops"),
			Size:             store.GetInt64Ptr("size"),
			Type:             store.GetStringPtr("type"),
			Encrypted:        store.GetBoolPtr("encrypted"),
			EncryptionKey:    store.GetStringPtr("encryptionKey"),
			Opts:             store,
		}

		serviceConfig := r.config.Scope(
			fmt.Sprintf("libstorage.server.services.%s", service.Name())

		if opts.Size == nil {
			i := serviceConfig.GetInt(
				"libstorage.server.api.volumes.create.size")
			opts.Size = &i
		}

		v, err := svc.Driver().VolumeCreate(ctx, store.GetString("name"), opts)
```

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/libstorage #459](https://github.com/codedellemc/libstorage/issues/459) via [**ZenHub**](https://www.zenhub.com/)
