### ISSUE TITLE
Allow one-liners for simplified CLI management

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/rexray#58]
There are cases where it is very nice to allow bulk commands by way of the CLI.  For example, if someone would like to remove all mapped volumes this should be possible via nested command as such.

`rexray volume unmount $(rexray volume map -q)`

Currently this would be accomplished with a command like `./rexray volume map | grep "volumeid:" | awk '": " { system("./rexray volume unmount --volumeid="$2); }'`.

**Comment by akutz** [comment]
Hi @clintonskitson, 

So you want Powershell, got it. :) 

To accomplish the above we need to establish a consistent output format for ALL commands with as many command, standard keys such as `id`, `name` as possible. In short, we need an operative model. Perhaps based on the interfaces or structs? Either way it becomes a little tricky as we would actually like to emit the data as JSON when piped back to another `REX-Ray` command as its stdin, but as plain-text when to the console's stdout.

**Comment by clintonskitson** [comment]
It could be simpler than that.. a global parameter such as `-q` could be used to limit the output to only IDs possibly.  These could then be easily consumed as a string[] arg I believe.

**Comment by akutz** [comment]
Hi @clintonskitson,

I agree, that's one possibility. However I was thinking of more than just this command. I was thinking of a way to pass all output data in a structured format so that receiving commands could parse it. 

Regarding your suggestion, if we were to implement something simple, what do you think of a flag called `-f`` or `--fields` that exists for any command that emits data. It would indicate to the command to emit the output as a series of CSV lines with a one-time header of the field names at the top. That would allow for structure and flexibility but also support your suggestion of just emitting IDs as `-f id` would output only the ID fields.

Still, I do think this deserves more attention than what I just described. I think it's a great idea, and I'd like  it to be uniformly supported across the entire product.

**Comment by ryandotclair** [comment]
In this particular case, I'd personally prefer for the unmount command to have an --all option. But I prefer simple straightforward bluntness over elegant 😀

**Comment by akutz** [comment]
Hi @ryandotclair,

Would you mind filing an issue requesting the `--all` option? I'd like to keep it separate from this discussion. It shouldn't be too hard to accommodate, so once you file it I'll handle it. Thank you.
