### ISSUE TITLE
AWS ebs free space

### ISSUE THREAD

**Issue by ildarmf** [codedellemc/rexray#623]
Hello!

Is it possible to know the amount of free space EBS volume?

Kind regards,
Ildar

**Comment by akutz** [comment]
That would be a great feature to add to the model. @cduchesne, please take note? Thanks!

**Comment by akutz** [comment]
Actually, giving it a second thought, no, there's no way to do this for EBS because it's a block storage system with no inspection into the FS layer which is what would be required.

**Comment by akutz** [comment]
Hi @ildarmf,

Out of curiosity, for what were you wanting to use the information? Also, were you considering some approach of how to make it available?

**Comment by akutz** [comment]
FWIW, here was my thinking with regards to why I closed this originally:

The free space data is a moveable target. The free-space is ever-changing. So sure, we could leverage the libStorage client to post that information about the file system's related volume to the server, but for what purpose? It may be stale before the request that posts it is even complete.

There is providing information and there is providing information on which decisions and actions can be made based on the value and validity of said information. While the information has value, there is no way to ensure or guarantee its validity in any timely manner and therefore reduces if not removes any otherwise value the information has. 

The only way this becomes useful IMO is if there is a way for the server to request that information about a volume on-demand when a client makes the request. Just like the way we get the latest local device map before sending it with any request that requires it, any API call that would give back size information should be getting the current size information. There's no way to do that with the client involved. Not unless it's a single client that we control and has a bi-comm channel with the server.

To do this and add value:

1. The back-end storage API has to be able to provide the information or
2. We must reliably be able to ask clients to provide it on-demand

The first isn't true for the majority of the platforms we support or intend to support and number two doesn't work in a world where we don't own the client completely as it would not be reliable otherwise. Information for information's sake isn't a good look. We need people to know it's also valid information. There's no way we can ensure that without one of the above.

Anyway, those are my thoughts on the matter. I'm interested to hear yours. Thank you!

**Comment by ildarmf** [comment]
Hello!

We need to monitor up to one percent.

I'll tell you, in order:
We have an instance running on it docker, inside docker mounted ebs volume. 

I would like get free space like 
rexray volume get $path
is it possible?

**Comment by akutz** [comment]
Hi @ildarmf,

Yes and no. It would be possible to do so for any volumes attached/mounted to the instance from which you're running the REX-Ray command, but not for remote volumes. This is because EBS is a block-based storage platform and so the file-system level information simply isn't available centrally since it cannot be inspected by looking at the block device until it is attached and mounted to an operating system that can read the file system on the block device.

With the above limitation is this still a feature you want to see?

**Comment by codenrhoden** [comment]
My .02... With the limitation that you can only gather this information from a host that has a device mounted, there is no point in adding it to rexray. If you are going to call rexray to get local file system free space, you might as well call `df`.

If we were planning to have a centralized libStorage service reach out to known clients and gather that information, that would be a different story. I doubt we are considering that. Thoughts?

**Comment by akutz** [comment]
Hi @codenrhoden,

I would close this issue due to lack of activity. I agree it isn't a viable feature at this time.

**Comment by ildarmf** [comment]
@codenrhoden @akutz  thank you!
