### ISSUE TITLE
Pool of Volumes

### ISSUE THREAD

**Issue by miry** [codedellemc/rexray#631]
I would like to have feature to  mount any free/available volume with same name. Example:

There are 3 AWS/EBS volumes with Name: `rexray-test`
- I run docker container with mapping `rexray-test` to container. And it should get the first(any) volume form the list. 

- Then I run another 2 containers with same volume name, and I expect to see 2 volumes mounted and 1 available. 

Currently it is not possible to do this at least for 0.3.3. 

```
docker: Error response from daemon: create rexray-test: VolumeDriver.Create: {"Error":"Too many volumes returned"}.
```

**Comment by kacole2** [comment]
@miry today that's not possible because this was built with the intention that stateful applications require access to a unique volume. Making this in a round-robin approach would essentially break an applications ability to recover from its last write to disk. If you can expand more on the use case we can take a deeper look.

Also, please use the latest version [0.6.3](https://github.com/codedellemc/rexray/releases) which has AWS for both EBS and EFS support.

**Comment by miry** [comment]
thank you @kacole2
