### ISSUE TITLE
Simplify the build tags

### ISSUE THREAD

**Issue by akutz** [codedellemc/rexray#874]
# Summary
REX-Ray currently supports the following build tags:

| Tag | Description |
|-----|-------------|
| `gofig` | Enables `github.com/akutz/gofig` as the configuration provider |
| `pflag` | Enables `github.com/spf13/pflag` as the drop-in replacement for Go's `flag` package |
| `rexray_build_type_agent` | Excludes the client and controller modes |
| `rexray_build_type_client` | Excludes the agent and controller modes |
| `rexray_build_type_controller` | Excludes the agent and client modes |

This issue proposes a simplification of the build tags.

# New Feature
The updated list of tags might look like the following:

| Tag | Description |
|-----|-------------|
| `agent` | Excludes the client and controller modes |
| `client` | Excludes the agent and controller modes |
| `controller` | Excludes the agent and client modes |

The `gofig` and `pflag` tags will be implicitly defined.

**Comment by codenrhoden** [comment]
A couple questions come to mind with this one.

If no build flags are specified, would the default be the all-in-one build?

The `gofig` flag came in from the idea that someone else using libStorage might want to provide their own configuration provider. While that hasn't happened (that we know of), is it still a concern? If yes, can they still do it?

If I'm understanding things correctly, I think the approach would be that while our build scripts may define `gofig` implicitly, if someone else wants to build without it, they can make their own build process. Is that correct?

And last question, is this at #875 tightly coupled, or can they be done independently? I know changing the build tags will necessitate a change in the Makefile, but I suspect this can be done first, then changing the Makefile targets can be done later. I ask in order to know if those issues can be tackled in separate sprints/releases.
