### ISSUE TITLE
ceph/rbd error: missing instance ID

### ISSUE THREAD

**Issue by JinsYin** [codedellemc/rexray#897]
Error response from daemon: VolumeDriver.Mount: {"Error":"missing instance ID"}

???

**Comment by codenrhoden** [comment]
Hi @JinsYin,

This issue gives us absolutely nothing to go on. When you create a new issue, a template is provided that details all the information required for us to debug a problem (what version are you running, what drivers, what's your config, provide detailed logs, etc.).

I'm going to close this issue so that if you choose to open a new one, you'll see the template again. Please do fill it out with the requested information. This is equivalent to "it doesn't work".
