### ISSUE TITLE
Create REX-Ray module for CSI Ident+Node+Controller Services

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/rexray#904]
# Summary
For initial CSI support, create a new REX-Ray module (or modules) that implement the CSI Identity, Node, and Controller services.

# New Feature
The module(s) listens on the given `CSI_ENDPOINT` for gRPC traffic, and translates that to our existing libStorage API.

The module (or modules) need to be configurable such that we can create the following "CSI plugins":

* node -- this plugin serves the Node and Identity RPCs
* controller -- this plugin serves the Controller and Identity RPCs
* node+controller -- this plugins serves all Node, Controller, and Identity RPCs

**Comment by akutz** [comment]
Hi @clintkitson / @codenrhoden / et. al,

Some topics I wish to discuss regarding the new CSI module:

## Existing Integration Workflow
What are your thoughts on how the Northbound Adapter (thanks @koensayr) for CSI will function with regards to the existing integration workflow. Should requests handled by the CSI module be handled by the same integration driver used by the Docker module? If so this means:

* Volumes created by the CSI module a root `data` directory.
* The CSI module can be configured with the same [Volume](http://libstorage.readthedocs.io/en/stable/user-guide/config/#volume-configuration) configuration properties that the Docker module can use.

## Default Module Configuration
Currently the CSI module has no analogue to a `default-docker` configuration, ex. `default-csi`. This is because the CSI specification does not define a default location for UNIX socket files. Should REX-Ray define a default location for a CSI socket file and in turn define a `default-csi` module that is configured if the REX-Ray standard or agent binaries run as services?

I personally think that REX-Ray could also drop the `default-docker` module configuration as well and move towards requiring explicit configurations for modules, but that would break backwards compatibility, so that's just an aside.

**Comment by clintkitson** [comment]
The `data` directory is intentionally not declared in the CSI specification. The workflow is somewhat different where the CO tells the plugin where to eventually get something mounted. I believe we would still use the `data` directory and do an additionally bind mount to the CO defined location from this `data` directory.

In terms of the integration driver, I don't think I have enough information one way or another. Obviously today it is an unused abstraction since there is only one driver. I think the priority is to ensure existing Docker/Mesos/Flex functionality works as is alongside the new CSI functionality.

**Comment by clintkitson** [comment]
Doesn't the CSI spec declare that the CO passes a socket location for the plugin where it should then place a socket file?

**Comment by akutz** [comment]
Hi @clintkitson,

Re: the socket location - yes it does, via the `CSI_ENDPOINT` environment variable. It's not a question of the absolute path but rather a default directory for the socket files, such as the one used by Docker.

**Comment by akutz** [comment]
Hi @clintkitson,

> The data directory is intentionally not declared in the CSI specification. The workflow is somewhat different where the CO tells the plugin where to eventually get something mounted. I believe we would still use the data directory and do an additionally bind mount to the CO defined location from this data directory.

That works for me. Effectively we're relocating the burden of understanding the limitations and requirements of the data consumer from REX-Ray to the CO. Thanks.

 > In terms of the integration driver, I don't think I have enough information one way or another. Obviously today it is an unused abstraction since there is only one driver. I think the priority is to ensure existing Docker/Mesos/Flex functionality works as is alongside the new CSI functionality.

You have all of the same information available to me :) The point is moot anyway. In the end the `data` directory component may have been the only real outlier in an otherwise fairly standard _attach_ / _format_ / _mount_ workflow.

**Comment by akutz** [comment]
Hi @clintkitson,

> Re: the socket location - yes it does, via the CSI_ENDPOINT environment variable. It's not a question of the absolute path but rather a default directory for the socket files, such as the one used by Docker.

Okay, if `CSI_ENDPOINT` is defined then a `default-csi` module will be initialized with the value of the former as the network address. Otherwise people can explicitly configure additional CSI modules if they wish.

**Comment by clintkitson** [comment]
If I am hearing you right, then we are saying that someone may under a centralization model decide to run multiple CSI endpoints from a single rexray instance?

**Comment by akutz** [comment]
I think what might be happening is that you're thinking of RR as a single process that starts to fulfill a role as a CSI endpoint. Remember that RR has an existing configuration method and that even the CSI_ENDPOINT env var could be out of scope of the RR binary itself, instead left to a wrapper.

The discussion is about the fact that multiple CSI modules *can* be configured via RR's module config. There is no way to support a default CSI module as we do Docker because the latter provides a default sock dir where our default module can write its socket.

As I said, at best we'd auto load a default CSI module if the aforementioned env var is detected. And a user could simply configure additional CSI modules via the RR config file.

This isn't about the use case alone as we're leveraging existing kit and workflows. I'm trying to decide how to manage the new with the old.

**Comment by clintkitson** [comment]
I feel the case where REX receives the `CSI_ENDPOINT` env var would determine it would only load a single module today would be ok.

**Comment by codenrhoden** [comment]
Closed by #975 and #998
