### ISSUE TITLE
[rexray/rbd plugin]can't mount the same volume on different host

### ISSUE THREAD

**Issue by mangobowl** [codedellemc/rexray#906]
I get the `rexray/rbd:0.9.2-rc2` plugin installed on host A and B:
`docker plugin install --grant-all-permissions --alias rbd rexray/rbd:0.9.2-rc2`

Host A and B are configured with the same ceph config, then create a `test` volume on host A
`docker volume create --driver rbd test`, after that host B will also see that volume.
If execute `docker run -d --name nginx -v test:/var/www/html nginx:1.10` on host A and B, the last one will cause error:
```shell
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/109ff45d6769d3408abb97234bbc546d5abb2234d1c8a2787e0568a0cee6ec89/rootfs': VolumeDriver.Mount: {"Error":"resource not found"}.
```

**Comment by codenrhoden** [comment]
Hi @mangobowl ,

Thanks so much for trying out the release candidate!

What you've described is just how the RBD driver works, and it's the same whether using the docker managed plugin like you did, or installing and running REX-Ray as a service. You cannot mount a block device on multiple machines at the same time, it will corrupt the filesystem. In your scenario, the container running on host A would have to be stopped before a similar `docker run` on host B using the same volume would be successful.

Some of the REX-Ray storage drivers support [*preemption*](http://libstorage.readthedocs.io/en/stable/user-guide/config/#preemption), which will cause host B to forcefully take the volume from host A when you start up the container. The Ceph driver does not support that because there is no central API in Ceph to attach/detach volumes from remote nodes -- all attach/detach operations have to be done via `rbd [un]map` commands local to the host -- hostB cannot remove a volume from hostA. 

Even if Ceph RBD did support preemption, the block device would still be attached on one host at a time. We have multi-host mounts in our roadmap, but there are caveats that go with it related to which hosts can have read-write access vs read-only.
